default_config:

automation: !include automation.yaml

homeassistant:
  name: Home
  unit_system: metric
  latitude: 51.107883
  longitude: 17.038538

logger:
  default: warning
  logs:
    homeassistant.components.mqtt: debug

lovelace:
  mode: storage
  dashboards:
    lovelace-yaml:
      mode: yaml
      title: Plants
      icon: mdi:sprout
      show_in_sidebar: true
      filename: plants_view.yaml

mqtt:
  broker: mosquitto
  port: 1883
  username: {{ mosquitto_username }}
  password: {{ mosquitto_password }}
  discovery: true
  discovery_prefix: homeassistant

notify:
  - name: ALL_DEVICES
    platform: group
    services:
      - service: mobile_app_iphone_kamil
      - service: mobile_app_iphone_domi

panel_iframe:
  node_red:
    title: Node Red
    icon: mdi:home-automation
    url: !env_var NODERED_ADDRESS

recorder:
  purge_keep_days: 30

sensor: !include sensor.yaml

sonoff:
  username: {{ sonoff_username }}
  password: {{ sonoff_password }}
  scan_interval: 60
  grace_period: 600
  api_region: eu
  entity_prefix: True
  debug: False
