- platform: mqtt
  name: "Living room temperature"
  state_topic: "home/living_room/conditions/general"
  unit_of_measurement: '°C'
  value_template: "{%raw%}{{ value_json.temp }}{%endraw%}"

- platform: mqtt
  name: "Living room humidity"
  state_topic: "home/living_room/conditions/general"
  unit_of_measurement: '%'
  value_template: "{%raw%}{{ value_json.humidity }}{%endraw%}"

- platform: mqtt
  name: "Living room illuminance"
  state_topic: "home/living_room/conditions/general"
  unit_of_measurement: '%'
  value_template: "{%raw%}{{ value_json.lux }}{%endraw%}"

- platform: mqtt
  name: "Coffea Arabica - soil moisture"
  state_topic: "home/plants/coffea_arabica"
  unit_of_measurement: '%'
  value_template: "{%raw%}{{ value_json.moisture }}{%endraw%}"
