- name: Install iptables
  apt:
    name: iptables
    state: latest
  become: true

- name: Set update-alternatives
  command: update-alternatives --set iptables /usr/sbin/iptables-legacy
  become: true

- name: Allow all loopback traffic
  iptables:
    action: append
    chain: INPUT
    in_interface: lo
    jump: ACCEPT
  become: true

- name: Allow established connections
  iptables:
    chain: INPUT
    ctstate: ESTABLISHED,RELATED
    jump: ACCEPT
  become: true

- name: Allow port ping traffic
  iptables:
    chain: INPUT
    jump: ACCEPT
    protocol: icmp
  become: true

- name: Allow port 22/SSH traffic
  iptables:
    chain: INPUT
    destination_port: 22
    jump: ACCEPT
    protocol: tcp
  become: true

- name: Allow port 1883/MQTT traffic
  iptables:
    chain: INPUT
    destination_port: 1883
    jump: ACCEPT
    protocol: tcp
  become: true

- name: Allow port 80/HTTP traffic
  iptables:
    chain: INPUT
    destination_port: 80
    jump: ACCEPT
    protocol: tcp
  become: true

- name: Allow port 443/HTTPS traffic
  iptables:
    chain: INPUT
    destination_port: 443
    jump: ACCEPT
    protocol: tcp
  become: true

- name: Drop any traffic without rule
  iptables:
    chain: INPUT
    jump: DROP
  become: true
