- name: apply common configuration to all nodes
  hosts: all
  remote_user: root
  roles:
    - common

- name: setup Docker engine
  hosts: docker
  remote_user: root
  roles:
    - docker

- name: run HomeAssistant app
  hosts: web
  remote_user: root
  roles:
    - web
