- name: apply common configuration to all nodes
  hosts: raspberry
  remote_user: root
  roles:
    - common

- name: setup Docker engine
  hosts: raspberry
  remote_user: root
  roles:
    - docker

- name: run HomeAssistant app
  hosts: raspberry
  remote_user: root
  roles:
    - web

- name: add HomeAssistant to autostart
  hosts: raspberry
  remote_user: root
  roles:
    - autostart
