version: '3'

services:
  homeassistant:
    container_name: homeassistant
    image: homeassistant/home-assistant:stable
    volumes:
      - ./config:/config
    environment:
      - TZ={{ timezone }}
      - "NODERED_ADDRESS=http://{{ local_ip }}:1880"
    restart: always
    ports:
      - 80:8123
    depends_on:
      - mosquitto
      - nodered

  mosquitto:
    image: eclipse-mosquitto
    hostname: mosquitto
    ports:
      - 1883:1883
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto.passwd:/etc/mosquitto/passwd

  nodered:
    image: nodered/node-red
    restart: unless-stopped
    environment:
      - TZ={{ timezone }}
    ports:
      - 1880:1880
    volumes:
      - ./nodered:/data
