---
# This playbook will install and configure mosquitto broker

- name: Install mosquitto client and broker
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
   - mosquitto
   - mosquitto-clients
  notify: stop mosquitto

- name: Copy mosquitto config 
  copy:
    src: mosquitto.conf
    dest: /etc/mosquitto/conf.d/mosquitto.conf

- name: Copy mosquitto.passwd file
  copy:
    src: mosquitto.passwd
    dest: /etc/mosquitto/passwd
  notify: start mosquitto
