---
# This playbook will install and configure webserver with Home Assistant
# https://www.home-assistant.io/docs/installation/docker/

- name: Check that the docker-compose exists
  stat:
    path: /home/pi/homeassistant/docker-compose.yml
  register: compose

- name: Down docker container
  command:
    chdir: /home/pi/homeassistant/
    cmd: docker-compose down
  when: compose.stat.exists
  become: true

- name: Create Home Assistant directory
  file:
    path: /home/pi/homeassistant/config
    state: directory
    mode: '0755'

- name: Copy Home Assistant config
  template:
    src: homeassistant_config/configuration.yaml
    dest: /home/pi/homeassistant/config/configuration.yaml

- name: Copy Home Assistant plants dashboard config
  template:
    src: homeassistant_config/plants_view.yaml
    dest: /home/pi/homeassistant/config/plants_view.yaml

- name: Copy Home Assistant automations config
  template:
    src: homeassistant_config/automation.yaml
    dest: /home/pi/homeassistant/config/automation.yaml

- name: Copy Home Assistant sensors config
  template:
    src: homeassistant_config/sensor.yaml
    dest: /home/pi/homeassistant/config/sensor.yaml

- name: Copy Home Assistant docker-compose
  template:
    src: docker-compose.yml
    dest: /home/pi/homeassistant/docker-compose.yml

- name: Copy mosquitto config
  template:
    src: mosquitto.conf
    dest: /home/pi/homeassistant/mosquitto.conf

- name: Copy mosquitto passwd
  template:
    src: mosquitto.passwd
    dest: /home/pi/homeassistant/mosquitto.passwd

- name: Remove existing custom components directory
  file:
    path: /home/pi/homeassistant/config/custom_components/
    state: absent
  become: true

- name: Clone sonoff integration
  git:
    repo: https://github.com/peterbuga/HASS-sonoff-ewelink.git
    dest: /home/pi/repos/HASS-sonoff-ewelink/

- name: Copy sonoff integration to custom components
  copy:
    src: /home/pi/repos/HASS-sonoff-ewelink/sonoff/
    dest: /home/pi/homeassistant/config/custom_components/sonoff/
    remote_src: true

- name: Create nodered directory
  file:
    path: /home/pi/homeassistant/nodered
    state: directory
    mode: '0755'

- name: Set owner of nodered directory
  command: chown -R pi:pi /home/pi/homeassistant/nodered/
  become: true

- name: Run docker container
  command:
    chdir: /home/pi/homeassistant/
    cmd: docker-compose up -d
  register: container
  become: true

- debug: msg="{{ container.stdout }}"
